global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['apigateway:8080']

  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice:8081']

  - job_name: 'activityservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['activityservice:8082']

  - job_name: 'aiservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aiservice:8083']